# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kogni', '0002_remove_scenariy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariy',
            name='image',
            field=models.ImageField(default=123456789, upload_to='kogni_images'),
            preserve_default=False,
        ),
    ]
