# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kogni', '0006_scenariy_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariy',
            name='image',
        ),
    ]
