# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kogni', '0007_remove_scenariy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariy',
            name='image',
            field=models.ImageField(blank=True, upload_to='kogni_images'),
        ),
    ]
