# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kogni', '0008_scenariy_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariy',
            name='image',
        ),
        migrations.AddField(
            model_name='scenariy',
            name='file',
            field=models.FileField(blank=True, upload_to='kogni_karti'),
        ),
    ]
