# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kogni', '0009_auto_20171014_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariy',
            name='image',
            field=models.ImageField(blank=True, upload_to='kogni_images'),
        ),
    ]
