# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kogni', '0010_scenariy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id_change', models.IntegerField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=30)),
                ('new_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id_iteration', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='K_map',
            fields=[
                ('id_map', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id_link', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=30)),
                ('target', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('k_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kogni.K_map')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id_node', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('k_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kogni.K_map')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id_reaction', models.IntegerField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=30)),
                ('new_value', models.FloatField()),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kogni.Iteration')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id_scenario', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('k_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kogni.K_map')),
            ],
        ),
        migrations.AddField(
            model_name='iteration',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kogni.Scenario'),
        ),
        migrations.AddField(
            model_name='change',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kogni.Iteration'),
        ),
    ]
