# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kogni', '0011_auto_20171117_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='iteration',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='link',
            name='k_map',
        ),
        migrations.RemoveField(
            model_name='node',
            name='k_map',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='k_map',
        ),
        migrations.DeleteModel(
            name='Change',
        ),
        migrations.DeleteModel(
            name='Iteration',
        ),
        migrations.DeleteModel(
            name='K_map',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
