# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kogni', '0012_auto_20171117_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_log',
            fields=[
                ('id_node', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Node_mar',
            fields=[
                ('id_node', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Node_men',
            fields=[
                ('id_node', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
            ],
        ),
    ]
